name = "arcane-visions"
account_id = "d82b44925438cd879407e73ac3105ca5"
compatibility_date = "2026-05-27"

[assets]
directory = "dist"
html_handling = "auto-trailing-slash"
not_found_handling = "404-page"
